In [1]:
import numpy as np
from cvxopt import matrix, solvers
#solvers.options['glpk'] = {'tm_lim': 1000} # max timeout for glpk

In [2]:
# Example Using cvxopt

<img src="cvxopt_example.png">

In [3]:
A = matrix([ [-1.0, -1.0, 0.0, 1.0], [1.0, -1.0, -1.0, -2.0] ])
b = matrix([ 1.0, -2.0, 0.0, 4.0 ])
c = matrix([ 2.0, 1.0 ])

In [4]:
sol=solvers.lp(c,A,b)

     pcost       dcost       gap    pres   dres   k/t
 0:  2.6471e+00 -7.0588e-01  2e+01  8e-01  2e+00  1e+00
 1:  3.0726e+00  2.8437e+00  1e+00  1e-01  2e-01  3e-01
 2:  2.4891e+00  2.4808e+00  1e-01  1e-02  2e-02  5e-02
 3:  2.4999e+00  2.4998e+00  1e-03  1e-04  2e-04  5e-04
 4:  2.5000e+00  2.5000e+00  1e-05  1e-06  2e-06  5e-06
 5:  2.5000e+00  2.5000e+00  1e-07  1e-08  2e-08  5e-08
Optimal solution found.


In [5]:
print(sol['x'])

[ 5.00e-01]
[ 1.50e+00]



In [6]:
# hw6, maxmin algo

In [7]:
def maxmin(A):
    num_vars = len(A)
    
    # minimize matrix c
    c = [-1] + [0 for i in range(num_vars)]
    c = np.array(c, dtype="float")
    c = matrix(c)
    
    # constraints G*x <= h
    G = np.matrix(A, dtype="float").T # reformat each variable is in a row
    # G before inverse sign to get the standard form
    print("G matrix:", G)
    G *= -1 # minimization constraint
    G = np.vstack([G, np.eye(num_vars) * -1]) # > 0 constraint for all vars
    new_col = [1 for i in range(num_vars)] + [0 for i in range(num_vars)]
    G = np.insert(G, 0, new_col, axis=1) # insert utility column for simplex tableau
    
    G = matrix(G)
    h = ([0 for i in range(num_vars)] + 
         [0 for i in range(num_vars)])
    h = np.array(h, dtype="float")
    h = matrix(h)
    
    # contraints Ax = b, sum of pi_rock, pi_paper, pi_scissors equal 1
    A = [0] + [1 for i in range(num_vars)]
    A = np.matrix(A, dtype="float")
    A = matrix(A)
    b = np.matrix(1, dtype="float")
    b = matrix(b)
    print("c matrix:", c)
    print("G matrix:", G)
    print("h matrix:", h)
    print("A matrix:", A)
    print("b matrix:", b)
    
    sol = solvers.lp(c=c, G=G, h=h, A=A, b=b)
    return sol

In [8]:
# A = [[0,1,-1], [-1,0,1],[1,-1,0]]
A = [[0, 2, -1], [-2, 0, 1] ,[1, -1, 0]]
# A = [[0.0, 1.0, -4.55], [-1.0, 0.0, 1.72], [4.55, -1.72, 0.0]]
# A = [[0.0, 1.0, -1.0], [-1.0, 0.0, 0.35], [1.0, -0.35, 0.0]]
# A = [[0.0, 4.82, -4.88], [-4.82, 0.0, 1.0], [4.88, -1.0, 0.0]]
# A = [[0.0, 4.0, -1.0], [-4.0, 0.0, 1.0], [1.0, -1.0, 0.0]]
# A = [[0.0, 1.0, -2.83], [-1.0, 0.0, 1.17], [2.83, -1.17, 0.0]]
# A = [[0.0, 3.05, -1.0], [-3.05, 0.0, 1.31], [1.0, -1.31, 0.0]]
# A = [[0.0, 1.0, -0.92], [-1.0, 0.0, 2.39], [0.92, -2.39, 0.0]]
# A = [[0.0, 0.11, -0.8], [-0.11, 0.0, 1.0], [0.8, -1.0, 0.0]]
# A = [[0.0, 1.0, -1.31], [-1.0, 0.0, 3.88], [1.31, -3.88, 0.0]]
# A = [[0.0, 0.7, -1.0], [-0.7, 0.0, 2.36], [1.0, -2.36, 0.0]]

In [9]:
G = np.matrix(A, dtype="float")
G

matrix([[ 0.,  2., -1.],
        [-2.,  0.,  1.],
        [ 1., -1.,  0.]])

In [10]:
G = np.matrix(A, dtype="float").T
G

matrix([[ 0., -2.,  1.],
        [ 2.,  0., -1.],
        [-1.,  1.,  0.]])

In [12]:
num_vars = len(A)
new_col = [1 for i in range(num_vars)] + [0 for i in range(num_vars)]
new_col

[1, 1, 1, 0, 0, 0]

In [14]:
print(matrix(G))

[ 0.00e+00 -2.00e+00  1.00e+00]
[ 2.00e+00  0.00e+00 -1.00e+00]
[-1.00e+00  1.00e+00  0.00e+00]



In [15]:
# get solution using maxmin algo
sol = maxmin(A=A)
probs = sol["x"]
print(probs)

G matrix: [[ 0. -2.  1.]
 [ 2.  0. -1.]
 [-1.  1.  0.]]
c matrix: [-1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]

G matrix: [ 1.00e+00  0.00e+00  2.00e+00 -1.00e+00]
[ 1.00e+00 -2.00e+00  0.00e+00  1.00e+00]
[ 1.00e+00  1.00e+00 -1.00e+00  0.00e+00]
[ 0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00]
[ 0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00]
[ 0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00]

h matrix: [ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]

A matrix: [ 0.00e+00  1.00e+00  1.00e+00  1.00e+00]

b matrix: [ 1.00e+00]

     pcost       dcost       gap    pres   dres   k/t
 0: -3.0502e-17 -2.5564e-17  9e+00  3e+00  4e+00  1e+00
 1: -2.9938e-02  2.9938e-02  2e-01  2e-01  4e-01  2e-01
 2: -2.2221e-04  2.2221e-04  4e-03  6e-03  9e-03  3e-03
 3: -2.2333e-06  2.2333e-06  4e-05  6e-05  9e-05  3e-05
 4: -2.2331e-08  2.2331e-08  4e-07  6e-07  9e-07  3e-07
 5: -2.2331e-10  2.2331e-10  4e-09  6e-09  9e-09  3e-09
Optimal solution found.
[ 2.23e-10]
[ 2.50e-01]
[ 2.50e-01]
[ 5.00e-01]



In [16]:
# get solution using maxmin algo
list(probs)[1:]

[0.25000000030253877, 0.2499999983752276, 0.5000000013222334]