In [1]:
import mdptoolbox
import numpy as np

In [2]:
# Example from TA on using mdptoolbox
prob = np.zeros((2, 5, 5))

prob[0] = [[0.3, 0.7, 0., 0., 0.],
           [0.3, 0.0, 0.7, 0., 0.],
           [0.3, 0.0, 0., 0.7, 0.],
           [0.3, 0.0, 0., 0., 0.7],
           [0.3, 0.0, 0., 0., 0.7]]

prob[1] = [[1., 0., 0., 0., 0.],
           [1., 0., 0., 0., 0.],
           [1., 0., 0., 0., 0.],
           [1., 0., 0., 0., 0.],
           [1., 0., 0., 0., 0.]]

rewards = np.zeros((5, 2))
rewards[0] = [0., 0.]
rewards[1] = [0., 1.]
rewards[2] = [0., 1.]
rewards[3] = [0., 1.]
rewards[4] = [0.3, 2.]

vi = mdptoolbox.mdp.ValueIteration(prob, rewards, 0.9)
vi.run()

optimal_policy = vi.policy
expected_values = vi.V

print(optimal_policy)
print(expected_values)

(0, 1, 1, 0, 1)
(3.1021779262212235, 3.7152970594035533, 3.7152970594035533, 3.732177926221223, 4.715297059403554)


In [3]:
# Manual Create transition matrix for case 
# Input: N = 6, isBadSide = {1,1,1,0,0,0}, Output: 2.5833

In [4]:
prob = np.zeros((2, 16, 16))

In [5]:
# Action 0 defined as rolling the die
# Action 1 defined as quit the game

prob[0][1][5:8] = 1/6.0

prob[0][5][9:12] = 1/6.0
prob[0][6][10:13] = 1/6.0
prob[0][7][11:14] = 1/6.0

prob[0][9][13:16] = 1/6.0
prob[0][10][14:16] = 1/6.0
prob[0][11][15:16] = 1/6.0

for i in range(0,16):
    prob[0][i][0] = 1 - np.sum(prob[0][i])


In [6]:
# check row sum equals 1 (requirement of mdptoolbox)
np.sum(prob[0],axis = 1)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [7]:
# transition probability for quit the game
# all state with determinstic proability of going to terminal state (column 0, first column)
prob[1][:,0] = 1.0
prob[1]

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0

In [8]:
# Get reward only take action of quit (withdraw the current bankroll)
rewards = np.zeros((16,2))

rewards[:,0] = 0
for i in range(1,16):
    rewards[i,1] = i - 1

rewards

array([[  0.,   0.],
       [  0.,   0.],
       [  0.,   1.],
       [  0.,   2.],
       [  0.,   3.],
       [  0.,   4.],
       [  0.,   5.],
       [  0.,   6.],
       [  0.,   7.],
       [  0.,   8.],
       [  0.,   9.],
       [  0.,  10.],
       [  0.,  11.],
       [  0.,  12.],
       [  0.,  13.],
       [  0.,  14.]])

In [9]:
# get the shape of Transition matrix P and Reward matrix R
print(prob.shape)
print(rewards.shape)
np.sum(prob[0],axis=1) - 1

(2, 16, 16)
(16, 2)


array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
        -1.11022302e-16,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00])

In [10]:
# calling value iteration, 1.0 is the discount rate defined in the quesiton
vi = mdptoolbox.mdp.ValueIteration(prob, rewards, 1.0)
vi.run()

optimal_policy = vi.policy
expected_values = vi.V

print(optimal_policy)
print(expected_values)

# Input: N = 6, isBadSide = {1,1,1,0,0,0}, Output: 2.5833

(0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1)
(0.0, 2.583333333333333, 1.0, 2.0, 3.0, 4.5, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0)


In [11]:
# Define N, x
# N is the number of side for the Die
# X is the defined upper bound of the value, empirically derived to be 2N+2
# state is defined as current bankroll from 0 to 2N+2
# one additional state (first column) as the terminal state
N = 9
x = N*2 + 2 + 2
x

22

In [12]:
# Get reward only take action of quit (withdraw the current bankroll)
rewards = np.zeros((x,2))

rewards[:,0] = 0
for i in range(1,x):
    rewards[i,1] = i - 1

rewards

array([[  0.,   0.],
       [  0.,   0.],
       [  0.,   1.],
       [  0.,   2.],
       [  0.,   3.],
       [  0.,   4.],
       [  0.,   5.],
       [  0.,   6.],
       [  0.,   7.],
       [  0.,   8.],
       [  0.,   9.],
       [  0.,  10.],
       [  0.,  11.],
       [  0.,  12.],
       [  0.,  13.],
       [  0.,  14.],
       [  0.,  15.],
       [  0.,  16.],
       [  0.,  17.],
       [  0.,  18.],
       [  0.,  19.],
       [  0.,  20.]])

In [13]:
# transition probability for quit the game
# all state with determinstic proability of going to terminal state (column 0, first column)
prob = np.zeros((2, x, x))
prob[1][:,0] = 1.0
prob[1]

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0., 

In [14]:
# creating list of reachable state, this is to automate the update of transition function
# when taking the rolling action 0

mask = np.array([0,0,1,0,1,1,1,0,1])
avil = set(np.where(mask != 1)[0]+1)
avil = list(avil)
final_set = avil.copy()
final_set.append(0)
print(avil)
print(final_set)       

[8, 1, 2, 4]
[8, 1, 2, 4, 0]


In [15]:
# constructing list of reachable state
for i in final_set:
    for j in avil:
        #print(i, j, i+j <= x, i+j, i+j in final_set)
        if i+j <= 2*N+2 and i+j not in final_set:
            final_set.append(i+j)
            #print(final_set)           
final_set = sorted(final_set)
print(final_set)            

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [16]:
print(final_set)
print(avil)
for i in final_set:
    for j in avil:
        if (i+j) <= 2*N+2:
            #print(i,j,i+j)
            prob[0][1+i][i+j+1] = 1.0/N

for i in range(0,x):
    prob[0][i][0] = 1 - np.sum(prob[0][i])    

prob[0]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[8, 1, 2, 4]


array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.55555556,  0.        ,  0.11111111,  0.11111111,  0.        ,
         0.11111111,  0.        ,  0.        ,  0.        ,  0.11111111,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.55555556,  0.        ,  0.        ,  0.11111111,  0.11111111,
         0.        ,  0.11111111,  0.        ,  0.        ,  0.        ,
         0.11111111,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.55555556

In [17]:
# check row sum equals 1 (requirement of mdptoolbox)
np.sum(prob[0], axis=1)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [18]:
# solve the mdp and generate the values of state
# second state is the state when bankroll equals 0, which is what the question asks

vi = mdptoolbox.mdp.ValueIteration(prob, rewards, 1.0)
vi.run()

optimal_policy = vi.policy
expected_values = vi.V

print(optimal_policy)
print(expected_values)

(0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
(0.0, 1.8587105624142661, 2.1728395061728394, 2.5555555555555554, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0)
